<script lang="ts">
  import {
    FeijoaColor,
    MalibuColor,
    FernColor,
    FlamingoColor,
    SeagullColor,
    SalmonColor,
    PlatinumColor,
    IconSize
  } from '@hcengineering/ui'

  export let value: number = 0
  export let size: IconSize = 'small'

  const dashClass =
    value > 0
      ? `segmented-progresscircle__circles__progress-dashes--${value}`
      : 'segmented-progresscircle__circles__progress-dashes'
  const colors = [SalmonColor, SeagullColor, MalibuColor, FeijoaColor, FernColor]
</script>

<div class="segmented-progresscircle">
  <div class="segmented-progresscircle__circles">
    <svg class="svg-{size}" viewBox="0 0 16 16">
      <circle r="7" cy="8" cx="8" stroke-width="2" class="segmented-progresscircle__circles__background-dashes">
      </circle>
      {#if value > 0}
        <circle
          r="7"
          cy="8"
          cx="8"
          style:stroke={colors[value - 1]}
          stroke-width="2"
          class="segmented-progresscircle__circles__progress-dashes {dashClass}"
        >
        </circle>
      {/if}
      >
    </svg>
  </div>
</div>

<style lang="scss">
  // =========================
  // How it works
  // =========================
  // We use and SVG with two circles. Both are dashed lines
  // with 10 steps/parts. One of these are gray and are always
  // shown (the gray one). The green show as many steps as it
  // should to act as a progressbar/to make it seem like the
  // grey parts are becoming green, but in reality it's just
  // green stuff above the grey.

  // The green cicle isn't always supposed to show all steps,
  // so for that we use the dasharray and set the spacing to
  // an extremly hight number. For example:
  // dasharray='25 5 25 5 25 5'
  // would make a dashed line with one style repeated three
  // times: A 25px long line with 5px spacing after it.
  // This won't cover the whole circle, so it will start to
  // repeat. To make it stop after three times/dashes, we
  // can use a really long space instead of the last 5:
  // dasharray='25 5 25 5 25 10000'
  // Since the circle isn't that bit it won't repeat.

  // ==============
  // The math for sizes of the lines
  // ==============
  // This is a bit of a trick but very handy as well.
  // The circle will have a readius of 59 (set in SVG circle
  // as an attribute r="59"). The circumference will then be
  // 59*2*3.1415 ~= 370.

  // OWASP (where this is used) have 10 different tests and
  // therefore it should have 10 steps. Each step then has
  // 370/10 amount of space each = 37. Each step needs the
  // actual progress line (the one that becomes green) and
  // the spacing to the next progress step.

  // We use spacing of 10 and line-lenght of 27 (=37).

  // ==============
  // How to use
  // ==============
  // Add the class 'segmented-progresscircle__circle--1' to show one step
  // as green. 'segmented-progresscircle__circle--2' for two green steps
  // etc.

  // Generate classes --1 to --10 (not --0)
  // and give the progress for each a dasharray, which is generated by a function
  @mixin generate-steps() {
    @for $i from 1 through 10 {
      &--#{$i} {
        stroke-dasharray: generate-dasharray($i);
      }
    }
  }

  // Generate a SVG dasharray for step-progress.

  @function generate-dasharray($step) {
    $stepSize: 5; // size of green/gray line
    $spacingSize: 3.7; // space between each line

    $dasharray: '';

    @for $i from 0 to $step {
      $dasharray: $dasharray + ' ' + $stepSize;

      // If it's the last step, add big spacing to prevent the dashing to repeat
      @if $i == $step - 1 {
        // 1000 = "random" high number (higher than the circumfence of the circle)
        $dasharray: $dasharray + ' 1000';

        // If it's not the last step, add normal spacing
      } @else {
        $dasharray: $dasharray + ' ' + $spacingSize;
      }
    }

    // Sass will for some reason quote the string, so unquote it before returing
    @return unquote($dasharray);
  }

  .segmented-progresscircle {
    position: relative;
    display: inline-block;

    circle {
      fill: transparent;
    }

    &__circles {
      // Rotate so the progress will start from the top.
      // Every example of round progress bars we could find
      // starts from 12 o'clock
      transform: rotate(-90deg);

      &__progress-dashes {
        stroke-linecap: round;
        stroke: #19e27a;

        // We have 10 steps/bars. If 0 progress is done, don't even bother to show
        // it
        &--0 {
          display: none;
        }

        // Use a mixin to generate the other progress steps
        @include generate-steps();
      }

      &__background-dashes {
        stroke-linecap: round;
        stroke: var(--theme-caption-color);
        opacity: 0.15;
        stroke-dasharray: generate-dasharray(5);
      }
    }
  }
</style>
